### ISSUE TITLE
New feature: Add additional RCON connection

### ISSUE THREAD

**Issue by nsonP** [wriley/beParser#4]
Add the function to register additional Rcon connections.
This way the parser could login in to additional servers and ban hackers. Making management of multiple servers easier.

Example:
Player X gets banned on Server 1. The parser then logs into Server 2 and bans Player X there also.

**Comment by wriley** [comment]
I think this functionality is best left to other RCON tools and ban sharing utilities. I don't want to turn this into a swiss army knife program but keep the focus on log scanning.
